# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe3208eeb104101ded3ec03c63e0ce5c6ca3e0ae4cf7e47b1bd735dbbbb9eb1ce631f19e7af59d12c4e4a1dc79e8fdca658d2e255c06dd58876121044a04476

test:
  secret_key_base: 9a0e1c7e36a91d440a9f4265b962403a62d8262cd809ce8b69cdf61ba0931295df5b895418f96dd152364fef7673cb1096964b9b7e3d92c076565f1cafc9f067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
